steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/prismatic-fact-455403-c4/social-platform:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/prismatic-fact-455403-c4/social-platform:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/social-platform', 'social-platform=gcr.io/prismatic-fact-455403-c4/social-platform:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=social-cluster'
images:
- 'gcr.io/prismatic-fact-455403-c4/social-platform:$COMMIT_SHA'