apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
  namespace: prod
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: gcr.io/prismatic-fact-455403-c4/web-server:latest
        command: ["node", "init-db.js"]
        env:
        - name: DB_HOST
          value: "database-svc.prod.svc.cluster.local"
        - name: DB_USER
          value: "mysqluser"
        - name: DB_PASSWORD
          value: "mysqlpassword"
        - name: DB_NAME
          value: "social_platform_db"
        volumeMounts:
        - name: credentials
          mountPath: "/app/credentials"
          readOnly: true
      volumes:
      - name: credentials
        secret:
          secretName: gcp-credentials
      restartPolicy: OnFailure
  backoffLimit: 4