apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storageclass
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
volumeBindingMode: WaitForFirstConsumer  # 关键：延迟绑定，直到 Pod 调度
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mysql-storageclass  # 使用新的 StorageClass